BEGIN;

CREATE TABLE IF NOT EXISTS travel_journal_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    password  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS journal(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES travel_journal_users(id),
    journal_title TEXT NOT NULL
);
CREATE TYPE page_type AS ENUM ('shoppinglist', 'wishlist', 'itinerary', 'daily entry', 'packinglist');
CREATE TABLE IF NOT EXISTS pages(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    journal_id INTEGER NOT NULL REFERENCES journal(id),
    page_type page_type NOT NULL,
    page_num INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS packing_list_title(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    packing_title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS packing_list_items(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    packing_item text NOT NULL,
    packing_item_checked BOOLEAN NOT NULL,
    packing_list_id INTEGER NOT NULL REFERENCES packing_list_title(id)
);
CREATE TABLE IF NOT EXISTS wishlist(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    page_id INTEGER REFERENCES pages(id)
);

CREATE TABLE IF NOT EXISTS wishlist_items(
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wishlist_item text NOT NULL,
    wishlist_item_checked BOOLEAN NOT NULL,
    wishlist_id INTEGER NOT NULL REFERENCES wishlist(id)

);
CREATE TABLE IF NOT EXISTS shopping_list(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    page_id INTEGER NOT NULL REFERENCES pages(id)
);

CREATE TABLE IF NOT EXISTS shopping_list_items(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shopping_list_id INTEGER NOT NULL REFERENCES shopping_list(id),
    shopping_item TEXT NOT NULL,
    shopping_item_checked BOOLEAN NOT NULL   
);

CREATE TABLE IF NOT EXISTS daily_entry(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    page_id INTEGER REFERENCES pages(id),
    picture TEXT NOT NULL,
    location TEXT NOT NULL,
    text_entry TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS itinerary(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    page_id INTEGER REFERENCES pages(id)    
);

CREATE TABLE IF NOT EXISTS itinerary_daily(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    itinerary_id INTEGER REFERENCES itinerary(id),
    travel_day INTEGER NOT NULL,
    daily_title TEXT NOT NULL,
    daily_destinations TEXT,
    date TIMESTAMPTZ

);

COMMIT;
